project_id = "ebzrddwipeogyffvlfqm"

[functions.login-with-username]
verify_jwt = false

[functions.notify-feedback]
verify_jwt = false

[functions.ai-fix-question]
verify_jwt = false

[functions.study-coach]
verify_jwt = false

[functions.ai-tutor]
verify_jwt = false

[functions.solution-path-analysis]
verify_jwt = false

[functions.homework-solver]
verify_jwt = false