// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_exams.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var EXAMS = [
  { id: "sat", name: "SAT", category: "College Admissions" },
  { id: "psat", name: "PSAT", category: "College Admissions" },
  { id: "act", name: "ACT", category: "College Admissions" },
  { id: "clt", name: "CLT", category: "College Admissions" },
  { id: "ap", name: "AP Exams (Biology, Calculus, Chemistry, Physics, US History, etc.)", category: "Advanced Placement" },
  { id: "ib", name: "IB", category: "International" },
  { id: "toefl", name: "TOEFL", category: "Language" },
  { id: "gmat", name: "GMAT", category: "Graduate Admissions" },
  { id: "lsat", name: "LSAT", category: "Graduate Admissions" },
  { id: "nclex", name: "NCLEX", category: "Professional" },
  { id: "teas", name: "TEAS", category: "Professional" },
  { id: "dat", name: "DAT", category: "Professional" },
  { id: "oat", name: "OAT", category: "Professional" },
  { id: "accuplacer", name: "ACCUPLACER", category: "Placement" },
  { id: "map", name: "MAP Growth", category: "K-12" },
  { id: "iowa", name: "Iowa / Stanford 10", category: "K-12" },
  { id: "terranova", name: "TerraNova", category: "K-12" }
];
var list_exams_default = defineTool({
  name: "list_exams",
  title: "List supported exams",
  description: "List all standardized exams and test categories supported by AlphaOmega.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EXAMS, null, 2) }],
    structuredContent: { exams: EXAMS }
  })
});

// src/lib/mcp/tools/get_study_tip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var TIPS = {
  sat: [
    "Pace: aim for ~82 seconds per math question and ~71 seconds per reading/writing question.",
    "For SAT Reading, always find explicit evidence in the passage before choosing.",
    "Skip and return: don't burn 3+ minutes on any single question."
  ],
  act: [
    "ACT Science rewards fast graph/table reading \u2014 don't over-read the passage first.",
    "ACT English tests concision: shorter answers are correct more often than chance."
  ],
  ap: [
    "For AP FRQs, always define terms and label units to earn every rubric point.",
    "Practice with authentic released FRQs; timing matters as much as content."
  ],
  general: [
    "Space your practice: 20 minutes daily beats 3 hours weekly.",
    "Review every wrong answer \u2014 the mistake journal is where real gains come from.",
    "Take a full-length timed practice test at least once every 2 weeks before test day."
  ]
};
var get_study_tip_default = defineTool2({
  name: "get_study_tip",
  title: "Get a study tip",
  description: "Get concise study and test-taking tips for a given exam family (sat, act, ap, or general).",
  inputSchema: {
    exam: z.enum(["sat", "act", "ap", "general"]).describe("Exam family.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ exam }) => {
    const tips = TIPS[exam] ?? TIPS.general;
    return {
      content: [{ type: "text", text: tips.map((t, i) => `${i + 1}. ${t}`).join("\n") }],
      structuredContent: { exam, tips }
    };
  }
});

// src/lib/mcp/tools/generate_practice_prompt.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var generate_practice_prompt_default = defineTool3({
  name: "generate_practice_prompt",
  title: "Generate a practice question prompt",
  description: "Return a structured prompt an assistant can use to generate an original practice question in AlphaOmega's style for a given exam, topic, and difficulty (1-10).",
  inputSchema: {
    exam: z2.string().min(1).describe("Exam id, e.g. 'sat', 'act', 'ap-biology'."),
    topic: z2.string().min(1).describe("Topic or skill, e.g. 'linear equations'."),
    difficulty: z2.number().int().min(1).max(10).describe("Difficulty 1-10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ exam, topic, difficulty }) => {
    const prompt = [
      `Write ONE original multiple-choice practice question for the ${exam.toUpperCase()} exam.`,
      `Topic: ${topic}. Difficulty: ${difficulty}/10.`,
      `- Question stem must match the style of official released ${exam.toUpperCase()} items.`,
      `- 4 choices labeled A-D (A-E for ACT). Exactly one correct answer.`,
      `- Include a 2-3 sentence explanation.`,
      `- Use exact values (radicals, \u03C0) not decimals for math.`,
      `- No LGBTQ+, sexual, alcohol, drug, or profane content.`
    ].join("\n");
    return {
      content: [{ type: "text", text: prompt }],
      structuredContent: { exam, topic, difficulty, prompt }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "alphaomega-mcp",
  title: "AlphaOmega Test Prep",
  version: "0.1.0",
  instructions: "Tools for AlphaOmega \u2014 a free test prep platform covering SAT, ACT, AP, IB, PSAT, GMAT, LSAT, NCLEX, TEAS, and 40+ K-12 and professional exams. Use `list_exams` to discover supported exams, `get_study_tip` for exam-specific tips, and `generate_practice_prompt` to build a prompt for producing an original practice question in AlphaOmega's style.",
  tools: [list_exams_default, get_study_tip_default, generate_practice_prompt_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
